// Self-host the two text fonts (IBM Plex Sans Arabic, Readex Pro) so there is no
// third-party origin at runtime — same as the local FontAwesome + ECharts. Text
// fonts go in assets/fonts/ (a sibling of, NOT inside, FontAwesome's icon
// webfonts folder). Downloads every subset (Arabic + Latin + latin-ext …) that
// Google Fonts serves for weights 400/600/700, then writes a local fonts.css
// with the unicode-range subsetting preserved and URLs rewritten to local files.
import { writeFileSync, mkdirSync } from 'node:fs';

const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36';
const OUT_DIR = new URL('../assets/fonts/', import.meta.url);
mkdirSync(OUT_DIR, { recursive: true });

const FAMILIES = [
  { name: 'IBM Plex Sans Arabic', slug: 'ibm-plex-sans-arabic', api: 'IBM+Plex+Sans+Arabic' },
  { name: 'Readex Pro', slug: 'readex-pro', api: 'Readex+Pro' },
];
const WEIGHTS = [400, 600, 700];
// This app renders only Arabic + Latin. Other subsets Google serves (cyrillic,
// vietnamese…) are gated by unicode-range and never fetched at runtime, so we
// skip them to keep the repo lean.
const KEEP_SUBSETS = new Set(['arabic', 'latin', 'latin-ext']);

async function getText(url) {
  const r = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!r.ok) throw new Error(`${r.status} ${url}`);
  return r.text();
}
async function getBuf(url) {
  const r = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!r.ok) throw new Error(`${r.status} ${url}`);
  return Buffer.from(await r.arrayBuffer());
}

let css = '/* Self-hosted text fonts (generated by tools/fetch-fonts.mjs). No CDN. */\n';
let fileCount = 0;

for (const fam of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${fam.api}:wght@${WEIGHTS.join(';')}&display=swap`;
  const src = await getText(url);
  // each face is preceded by a /* subset */ comment
  const blockRe = /\/\*\s*([\w\[\]-]+)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;
  let m;
  while ((m = blockRe.exec(src))) {
    const subset = m[1].replace(/[^\w-]/g, '');
    if (!KEEP_SUBSETS.has(subset)) continue;
    const body = m[2];
    const weight = (body.match(/font-weight:\s*(\d+)/) || [])[1];
    const woff2 = (body.match(/url\((https:\/\/[^)]+\.woff2)\)/) || [])[1];
    const range = (body.match(/unicode-range:\s*([^;]+);/) || [])[1];
    if (!weight || !woff2) continue;
    const file = `${fam.slug}-${weight}-${subset}.woff2`;
    writeFileSync(new URL(file, OUT_DIR), await getBuf(woff2));
    fileCount++;
    css += `@font-face {\n` +
      `  font-family: '${fam.name}';\n` +
      `  font-style: normal;\n` +
      `  font-weight: ${weight};\n` +
      `  font-display: swap;\n` +
      `  src: url(./${file}) format('woff2');\n` +
      (range ? `  unicode-range: ${range};\n` : '') +
      `}\n`;
    process.stdout.write(`\r${fam.slug}: ${fileCount} files`);
  }
}
console.log();
writeFileSync(new URL('fonts.css', OUT_DIR), css);
console.log(`wrote assets/fonts/fonts.css + ${fileCount} woff2 files`);
